Update for sdk 3.0.0
shripal17/dart_scorm pull request #5
Opened 2023-07-29 08:15 UTC by codesnik

Hey. Thanks for the good work, your package helped me a lot to understand how flutter can help with SCORM. Our project is already on 3.0.0, so we need an updated package.

I'm new to flutter, so I basically went through `dart analyze` and fixed warnings, mostly by slapping ? and !
This probably makes API slightly more awkward to use, so suggestions are welcome.

2023-07-29 19:59 UTC, shripal17 requested changes
Thank you 🚀

2023-07-29 19:59 UTC, shripal17 commented on lib/src/scorm_api.dart
> +  static ScormVersion? _version = null;
I would prefer it to be `late` instead of nullable, as the version is one thing without which rest of the functionality will break

2023-07-29 19:59 UTC, shripal17 commented on pubspec.yaml
> +version: 0.2.0
The version change can be major: `1.0.0`
I previously kept it as `0.1.0` as I was not sure if it supports everyone's use case.

2023-07-29 19:59 UTC, shripal17 commented on pubspec.yaml
> +# author: shripal17
Any particular reason for removing this?

2023-08-02 00:37 UTC, codesnik commented on pubspec.yaml
> +# author: shripal17
`dart analyze` says
```
warning • pubspec.yaml:5:1 • The 'author' field is no longer used and can be removed. Try removing the field. • deprecated_field
```
it looks like the field wasn't meant for credits but for authorizing package publishing, which is done differently nowadays. I can leave it untouched in the PR if you want, it's just a warning, after all.

2023-08-02 01:12 UTC, codesnik commented on example/lib/main.dart
> +                Visibility(visible: ScormAPI.apiFound, child: Text(ScormAPI.apiFound ? ScormAPI.version.toString() : '')),
had to do this to avoid "version is unitialized" error

2023-08-02 08:53 UTC, shripal17 approved these changes
🚀 Thank you

2023-08-02 08:53 UTC, merged

2023-08-02 08:55 UTC, shripal17 commented
I will publish the update on pub.dev in sometime

2023-08-03 07:26 UTC, codesnik commented
Thank you!